import crypto from 'crypto'

const toTitle = (s) => s.split(/\s+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
const toSlug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const deriveBrand = (intent) => {
  const lower = String(intent).toLowerCase()
  const words = lower.split(/[^a-z0-9]+/g).filter(Boolean)
  const stop = new Set(['the','and','app','api','service','game','tool','cli','web','site','mobile','dashboard'])
  const core = words.filter(w => !stop.has(w)).slice(0, 2).join(' ')
  const name = toTitle(core || 'Xandria')
  const slug = toSlug(name)
  let palette = { primary: '#00ff41', secondary: '#008F11', bg: '#0d0208', text: '#e0e0e0', accent: '#00e0ff' }
  if (/finance|saas|biz|commerce/.test(lower)) palette = { primary: '#16a34a', secondary: '#065f46', bg: '#0b1020', text: '#e6f3ff', accent: '#22d3ee' }
  else if (/health|med|care|bio/.test(lower)) palette = { primary: '#3b82f6', secondary: '#1e40af', bg: '#0a0f1e', text: '#e6f3ff', accent: '#a855f7' }
  else if (/creative|design|studio|art/.test(lower)) palette = { primary: '#f59e0b', secondary: '#b45309', bg: '#0b0b0b', text: '#f5f5f5', accent: '#ef4444' }
  else if (/gaming|fps|rpg|three|phaser|space|cyber/.test(lower)) palette = { primary: '#00ff41', secondary: '#00e0ff', bg: '#050505', text: '#e0ffe6', accent: '#ff00e0' }
  const tagline = `Built for ${name}`
  return { name, slug, palette, tagline }
}

export function synthesizeSpec(intent) {
  const lower = String(intent).toLowerCase()
  const isGame = /\b(game|rpg|fps|shooter|three|phaser)\b/.test(lower)
  const isWebApp = /\b(app|dashboard|web|react|next)\b/.test(lower)
  const isApi = /\b(api|server|service|node)\b/.test(lower)
  const isCli = /\b(cli|tool|utility)\b/.test(lower)
  const isMobile = /\b(mobile|ios|android|capacitor)\b/.test(lower)
  const wantsLLM = /\b(llm|ai|gpt|chatbot|assistant)\b/.test(lower)

  const type = isGame ? 'game' : isWebApp ? 'web-app' : isApi ? 'api' : isCli ? 'cli' : isMobile ? 'mobile' : 'web-app'

  const stack = []
  if (type === 'web-app') stack.push('React + Vite', 'Tailwind', 'Router')
  if (type === 'api') stack.push('Node.js', 'Express', 'Joi')
  if (type === 'game') stack.push('Three.js', 'React Three Fiber')
  if (type === 'cli') stack.push('Commander', 'Inquirer')
  if (type === 'mobile') stack.push('React', 'Capacitor')
  if (wantsLLM) stack.push('LLM Gateway')

  const features = []
  if (type === 'web-app') features.push('Auth', 'Dashboard', 'Settings', 'Responsive UI')
  if (type === 'api') features.push('REST endpoints', 'Validation', 'Error handling', 'Health check')
  if (type === 'game') features.push('Scene', 'Player', 'Enemy AI', 'HUD')
  if (type === 'cli') features.push('Init command', 'Info command')
  if (type === 'mobile') features.push('Native bridge', 'Safe area UI')
  if (wantsLLM) features.push('Chat endpoint', 'Provider switch')

  const modules = []
  if (type === 'web-app') modules.push('Layout', 'Pages: Dashboard, Settings')
  if (type === 'api') modules.push('Controllers', 'Routes', 'Middleware')
  if (type === 'game') modules.push('Scene', 'Store', 'Systems')
  if (type === 'cli') modules.push('Bin', 'Commands')
  if (type === 'mobile') modules.push('Capacitor config', 'App shell')

  const brand = deriveBrand(intent)
  return { id: crypto.randomUUID(), type, stack, features, modules, wantsLLM, intent, brand }
}

export function toPRD(spec) {
  return `# Product Requirements Document\n\n- ID: ${spec.id}\n- Intent: ${spec.intent}\n- Type: ${spec.type}\n\n## Goals\n- Generate a high-quality ${spec.type} aligned with intent\n- Provide production-ready scaffolding, tooling, and docs\n\n## Stack\n- ${spec.stack.join('\n- ')}\n\n## Features\n- ${spec.features.join('\n- ')}\n\n## Modules\n- ${spec.modules.join('\n- ')}\n\n## Quality\n- Linting, formatting, tests, CI, docs\n`
}

export function toArchitecture(spec) {
  return `# Technical Architecture\n\n## Overview\nThis artifact is generated by XANDRIA in unison with SOLOcoder specification synthesis.\n\n## Layers\n- UI / Interface (if applicable)\n- Domain / Game Logic (if applicable)\n- API / Services (if applicable)\n- Infrastructure: build, tooling, CI\n\n## Directories\n- src/: application source\n- public/: static assets (web)\n- config/: environment and service configs\n- tests/: unit/integration tests\n- docs/: product and architecture docs\n- .github/workflows/: CI pipelines\n\n## Notes\n- LLM gateway optional if wantsLLM = ${spec.wantsLLM}\n- Templates selected by intent, refined by spec.type\n\n## Branding\n- Name: ${spec.brand.name}\n- Slug: ${spec.brand.slug}\n- Palette: ${JSON.stringify(spec.brand.palette)}\n`
}
